spring:
    application:
        name: employee_management

    datasource:
        url: jdbc:mysql://localhost:3306/employee_management?createDatabaseIfNotExist=true
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true